name: Update Awesome Stars

on:
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │                                   
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        * * * * *
    - cron: '0 8/4 * * *'
  workflow_dispatch:

jobs:
  awesome-stars:
    name: Update Awesome Stars
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install starred

      - name: Update star list
        run: starred --username ${{ github.repository_owner }} --sort --token ${{ secrets.GITHUB_TOKEN }} > AWESOME-STARS.md

      - name: Setup Git
        uses: MedzikUser/action-setup-git@v0
        with:
          user: "awesome-stars"

      - name: Commit changes
        run: |
          git add .
          git diff-index --quiet HEAD || git commit -m "⭐ Update awesome stars"

      - name: Pull changes
        run: git pull -r

      - name: Push changes
        uses: ad-m/github-push-action@b007e7b818e33b04afd056e4c4b57ba917145d7a
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main'
